### ISSUE TITLE
Tracking pixel is being cached in browser

### ISSUE THREAD

**Issue by ChrisSargent** [EmpyrNetwork/empyr_web#5]
Because this script is using an image for the tracking, the browser is caching the network calls with the same parameters, meaning that you are not seeing the real usage data. e.g. if a user visits the same offer multiple times, you will only get one 'hit' for that user and pixel. e.g. if a user visit an offer detail page for offer ID 5382, and then at some point later visits it several times that day, you only get 1 hit for that day (looks like you have the images' cache control set to one day)

<img width="684" alt="Screen Shot 2019-04-29 at 09 19 20" src="https://user-images.githubusercontent.com/12176122/56881320-552e1980-6a60-11e9-9707-f51452d3b010.png">

**Comment by jcuzens** [comment]
This is the intended behavior at this time. We are distinctly counting these on the backend per user, per day per offer per view type to try to not over-inflate the view counts while also not burdening the browser with too many requests.
